require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });
const bcrypt = require('bcryptjs');
const slugify = require('slugify');
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const seedData = async () => {
  try {
    console.log('Clearing existing data...');
    await prisma.quizRecommendation.deleteMany();
    await prisma.quizAnswer.deleteMany();
    await prisma.quizOption.deleteMany();
    await prisma.quizQuestion.deleteMany();
    await prisma.quizResponse.deleteMany();
    await prisma.quiz.deleteMany();
    await prisma.orderItem.deleteMany();
    await prisma.order.deleteMany();
    await prisma.product.deleteMany();
    await prisma.category.deleteMany();
    await prisma.user.deleteMany();

    const salt = await bcrypt.genSalt(10);

    const admin = await prisma.user.create({
      data: {
        name: 'Admin',
        email: process.env.INITIAL_ADMIN_EMAIL || 'admin@blissnepal.com',
        password: await bcrypt.hash(process.env.INITIAL_ADMIN_PASSWORD || 'admin123', salt),
        role: 'admin',
        phone: '9800000000',
      },
    });
    console.log('✅ Admin user created:', admin.email);

    const customer = await prisma.user.create({
      data: {
        name: 'Demo Customer',
        email: 'customer@demo.com',
        password: await bcrypt.hash('customer123', salt),
        role: 'customer',
        phone: '9800000001',
      },
    });
    console.log('✅ Demo customer created:', customer.email);

    const catData = [
      { nameEn: 'Vibrators', nameNe: 'भाइब्रेटरहरू', slug: 'vibrators', descriptionEn: 'Premium vibrators for intimate pleasure', descriptionNe: 'आनन्दको लागि प्रीमियम भाइब्रेटरहरू' },
      { nameEn: 'Massagers', nameNe: 'मसाजरहरू', slug: 'massagers', descriptionEn: 'Relaxing body and intimate massagers', descriptionNe: 'आरामदायी शरीर र आन्तरिक मसाजरहरू' },
      { nameEn: 'Lubricants', nameNe: 'लुब्रिकेन्टहरू', slug: 'lubricants', descriptionEn: 'High-quality personal lubricants', descriptionNe: 'उच्च गुणस्तरको व्यक्तिगत लुब्रिकेन्टहरू' },
      { nameEn: 'Accessories', nameNe: 'सहायक सामग्री', slug: 'accessories', descriptionEn: 'Intimate accessories and essentials', descriptionNe: 'आन्तरिक सहायक सामग्री र आवश्यक सामान' },
      { nameEn: 'Wellness', nameNe: 'स्वास्थ्य', slug: 'wellness', descriptionEn: 'Sexual wellness and health products', descriptionNe: 'यौन स्वास्थ्य र कल्याण उत्पादनहरू' },
      { nameEn: 'Lingerie', nameNe: 'लन्जरी', slug: 'lingerie', descriptionEn: 'Sensual lingerie and apparel', descriptionNe: 'कामुक लन्जरी र पहिरन' },
    ];

    const categories = [];
    for (const c of catData) {
      const cat = await prisma.category.create({ data: c });
      categories.push(cat);
    }
    console.log(`${categories.length} categories created`);

    const products = [
      { nameEn: 'Silk Touch Vibrator', nameNe: 'सिल्क टच भाइब्रेटर', slug: 'silk-touch-vibrator', descriptionEn: 'Experience pure bliss with our premium silicone vibrator. Features 10 vibration modes, waterproof design, and USB rechargeable battery. Whisper-quiet motor for discreet pleasure.', descriptionNe: 'हाम्रो प्रीमियम सिलिकोन भाइब्रेटरसँग शुद्ध आनन्दको अनुभव गर्नुहोस्।', price: 4500, comparePrice: 6000, images: ['/uploads/silk_touch_vibrator.png'], categoryId: categories[0].id, tags: ['bestseller', 'waterproof', 'rechargeable'], stock: 25, featured: true, theme: 'champagne', specifications: { materials: 'Body-safe silicone, ABS', finish: 'Satin matte', frequency: '100 Hz', battery: 'Li-Ion 500mAh', charging: '2 hours at 5.0 V', userTime: 'Up to 2 hours', noiseLevel: 'Less than 50 dB', size: '120 x 38 x 38 mm', weight: '95g' }, colors: [{ name: 'Champagne Gold', hex: '#E6D3C1' }, { name: 'Midnight Black', hex: '#1A1A1A' }] },
      { nameEn: 'Rose Petal Massager', nameNe: 'रोज पेटल मसाजर', slug: 'rose-petal-massager', descriptionEn: 'Elegant rose-shaped massager with gentle suction and vibration. Perfect for intimate relaxation sessions. Medical-grade silicone, body-safe materials.', descriptionNe: 'कोमल चूसन र कम्पनसँग सुन्दर गुलाब आकारको मसाजर।', price: 3800, comparePrice: 5000, images: ['/uploads/rose_petal_massager.png'], categoryId: categories[1].id, tags: ['new', 'body-safe'], stock: 30, featured: true, theme: 'rose-gold', specifications: { materials: 'Medical-grade silicone', finish: 'Soft-touch velvet', frequency: '120 Hz', battery: 'Li-Ion 320mAh', charging: '1.5 hours', userTime: 'Up to 1.5 hours', noiseLevel: 'Less than 45 dB', size: '85 x 60 x 60 mm', weight: '78g' }, colors: [{ name: 'Blush Pink', hex: '#F2D5D0' }, { name: 'Rose Gold', hex: '#D4736E' }] },
      { nameEn: 'Aqua Glide Lubricant', nameNe: 'एक्वा ग्लाइड लुब्रिकेन्ट', slug: 'aqua-glide-lubricant', descriptionEn: 'Water-based personal lubricant that provides long-lasting smoothness. Hypoallergenic, pH balanced, and compatible with all toys. 100ml bottle.', descriptionNe: 'पानी-आधारित व्यक्तिगत लुब्रिकेन्ट जसले लामो समयसम्म चिल्लोपन प्रदान गर्दछ।', price: 1200, comparePrice: 1500, images: ['/uploads/aqua_glide_lubricant.png'], categoryId: categories[2].id, tags: ['water-based', 'hypoallergenic'], stock: 100, featured: true, theme: 'default', specifications: { materials: 'Water-based, glycerine-free', finish: 'Crystal clear liquid', frequency: 'N/A', battery: 'N/A', charging: 'N/A', userTime: 'N/A', noiseLevel: 'Silent', size: '100ml', weight: '120g' }, colors: [{ name: 'Clear', hex: '#FFFFFF' }] },
      { nameEn: 'Velvet Dreams Vibrator', nameNe: 'भेलभेट ड्रिम्स भाइब्रेटर', slug: 'velvet-dreams-vibrator', descriptionEn: 'Dual-motor vibrator with flexible neck for targeted stimulation. 12 patterns, memory function, and travel lock. Comes in a discreet storage pouch.', descriptionNe: 'लक्षित उत्तेजनाको लागि लचिलो घाँटीसँग डुअल-मोटोर भाइब्रेटर।', price: 5500, comparePrice: 7000, images: ['/uploads/velvet_dreams_vibrator.png'], categoryId: categories[0].id, tags: ['premium', 'dual-motor'], stock: 15, featured: true, theme: 'midnight', specifications: { materials: 'Body-safe silicone, ABS', finish: 'Sleek matte', frequency: '95 Hz', battery: 'Li-Ion 600mAh', charging: '2 hours', userTime: 'Up to 3 hours', noiseLevel: 'Less than 50 dB', size: '180 x 42 x 35 mm', weight: '145g' }, colors: [{ name: 'Deep Purple', hex: '#583D72' }, { name: 'Midnight Blue', hex: '#1C2B42' }, { name: 'Classic Black', hex: '#111111' }] },
      { nameEn: 'Satin Bliss Massage Oil', nameNe: 'साटिन ब्लिस मसाज तेल', slug: 'satin-bliss-massage-oil', descriptionEn: 'Aromatic massage oil with natural ingredients. Creates a sensual atmosphere for intimate moments. Non-greasy formula that absorbs beautifully into skin.', descriptionNe: 'प्राकृतिक तत्वहरूसँग सुगन्धित मसाज तेल।', price: 1800, comparePrice: 0, images: ['/uploads/satin_bliss_massage_oil.png'], categoryId: categories[1].id, tags: ['natural', 'aromatic'], stock: 50, featured: false, theme: 'gold', specifications: { materials: 'Natural seed oils, essential extracts', finish: 'Silky smooth oil', frequency: 'N/A', battery: 'N/A', charging: 'N/A', userTime: 'Long-lasting', noiseLevel: 'Silent', size: '50ml', weight: '70g' }, colors: [{ name: 'Amber Gold', hex: '#D4AF37' }] },
      { nameEn: 'Intimate Care Kit', nameNe: 'इन्टिमेट केयर किट', slug: 'intimate-care-kit', descriptionEn: 'Complete wellness kit including toy cleaner, storage bag, and care guide. Keep your intimate items clean and well-maintained.', descriptionNe: 'पूर्ण स्वास्थ्य किट जसमा ट्वॉय क्लिनर, भण्डारण झोला, र हेरचाह गाइड समावेश छ।', price: 2200, comparePrice: 2800, images: ['/uploads/satin_bliss_massage_oil.png'], categoryId: categories[4].id, tags: ['kit', 'hygiene'], stock: 40, featured: false, theme: 'default', specifications: { materials: 'Body-safe plastic, micro-fiber pouch', finish: 'Assorted premium products', frequency: 'N/A', battery: 'N/A', charging: 'N/A', userTime: 'N/A', noiseLevel: 'Silent', size: 'Various', weight: '350g' }, colors: [{ name: 'Classic White', hex: '#FFFFFF' }] },
      { nameEn: 'Midnight Lace Set', nameNe: 'मिडनाइट लेस सेट', slug: 'midnight-lace-set', descriptionEn: 'Elegant black lace lingerie set with adjustable straps. Available in multiple sizes. Soft, comfortable fabric for all-night wear.', descriptionNe: 'समायोज्य पट्टासहित सुन्दर कालो लेस लन्जरी सेट।', price: 3200, comparePrice: 4000, images: ['/uploads/rose_petal_massager.png'], categoryId: categories[5].id, tags: ['lingerie', 'lace'], stock: 20, featured: true, theme: 'dark', specifications: { materials: '90% Nylon, 10% Spandex lace', finish: 'Delicate sheer lace', frequency: 'N/A', battery: 'N/A', charging: 'N/A', userTime: 'All-night wear', noiseLevel: 'Silent', size: 'S, M, L, XL', weight: '60g' }, colors: [{ name: 'Midnight Black', hex: '#1A1A1A' }, { name: 'Ruby Red', hex: '#8B0000' }] },
      { nameEn: 'Couples Pleasure Set', nameNe: 'कपल्स प्लेजर सेट', slug: 'couples-pleasure-set', descriptionEn: 'Designed for shared pleasure. Includes vibrating ring and remote control. Enhance intimacy with your partner. Body-safe, rechargeable.', descriptionNe: 'साझा आनन्दको लागि डिजाइन गरिएको। कम्पन रिङ र रिमोट कन्ट्रोल समावेश।', price: 6500, comparePrice: 8000, images: ['/uploads/velvet_dreams_vibrator.png'], categoryId: categories[3].id, tags: ['couples', 'remote-control'], stock: 10, featured: true, theme: 'midnight', specifications: { materials: 'Medical-grade silicone, ABS', finish: 'Satin smooth', frequency: '110 Hz', battery: 'Li-Ion 250mAh', charging: '1 hour', userTime: 'Up to 1.5 hours', noiseLevel: 'Less than 45 dB', size: '75 x 40 x 30 mm', weight: '45g' }, colors: [{ name: 'Deep Purple', hex: '#583D72' }, { name: 'Midnight Blue', hex: '#1C2B42' }] },
      { nameEn: 'Premium Clitoral Vibrator', nameNe: 'प्रीमियम क्लिटोरल भाइब्रेटर', slug: 'premium-clitoral-vibrator', descriptionEn: 'Precision-designed for targeted pleasure. 8 intensity levels, whisper quiet, fully waterproof. Perfect for beginners and experienced users.', descriptionNe: 'लक्षित आनन्दको लागि सटीक डिजाइन। 8 तीव्रता स्तर, बहुत शांत, पूरी तरह जलरोधी।', price: 3500, comparePrice: 4500, images: ['/uploads/silk_touch_vibrator.png'], categoryId: categories[0].id, tags: ['beginner-friendly', 'clitoral'], stock: 35, featured: false, theme: 'champagne', specifications: { materials: 'Body-safe silicone', finish: 'Soft matte', frequency: '90 Hz', battery: 'Li-Ion 380mAh', charging: '1.5 hours', userTime: 'Up to 2 hours', noiseLevel: 'Less than 55 dB', size: '95 x 32 x 32 mm', weight: '65g' }, colors: [{ name: 'Soft Pink', hex: '#FFB6C1' }, { name: 'Pearl White', hex: '#F5F5F5' }] },
      { nameEn: 'Luxury Rabbit Vibrator', nameNe: 'लक्जरी रेबिट भाइब्रेटर', slug: 'luxury-rabbit-vibrator', descriptionEn: 'Dual stimulation rabbit design with rotating beads. 10 vibration modes + 5 rotation speeds. Premium gift packaging included.', descriptionNe: 'घुमाउने मोतीसँग डुअल स्टिमुलेशन खरहर डिजाइन।', price: 7200, comparePrice: 9000, images: ['/uploads/rose_petal_massager.png'], categoryId: categories[0].id, tags: ['luxury', 'dual-stimulation'], stock: 12, featured: true, theme: 'rose-gold', specifications: { materials: 'Body-safe silicone, ABS', finish: 'Glossy premium', frequency: '105 Hz', battery: 'Li-Ion 750mAh', charging: '2.5 hours', userTime: 'Up to 3.5 hours', noiseLevel: 'Less than 52 dB', size: '200 x 45 x 40 mm', weight: '180g' }, colors: [{ name: 'Rose Gold', hex: '#B76E79' }, { name: 'Pearl', hex: '#FDEEF4' }] },
      { nameEn: 'Wand Massager Pro', nameNe: 'वान्ड मसाजर प्रो', slug: 'wand-massager-pro', descriptionEn: 'Professional-grade wand massager for broad stimulation. Flexible head, multiple speeds, whisper-quiet motor. Perfect for couples play.', descriptionNe: 'व्यापक उत्तेजनाको लागि व्यावसायिक-गुणस्तरको वान्ड मसाजर।', price: 5800, comparePrice: 7200, images: ['/uploads/velvet_dreams_vibrator.png'], categoryId: categories[1].id, tags: ['couples', 'professional'], stock: 18, featured: false, theme: 'midnight', specifications: { materials: 'Silicone head, ABS handle', finish: 'Matte black', frequency: '120 Hz', battery: 'Li-Ion 800mAh', charging: '2 hours', userTime: 'Up to 4 hours', noiseLevel: 'Less than 48 dB', size: '250 x 60 x 60 mm', weight: '220g' }, colors: [{ name: 'Midnight Black', hex: '#0A0A0A' }, { name: 'Gunmetal Gray', hex: '#404040' }] },
      { nameEn: 'Sensual Warming Gel', nameNe: 'संवेदनशील वार्मिंग जेल', slug: 'sensual-warming-gel', descriptionEn: 'Warming lubricant that increases sensitivity. Creates tingling sensation for enhanced pleasure. Water-based, non-sticky formula.', descriptionNe: 'वार्मिंग लुब्रिकेन्ट जो संवेदनशीलता बढाता है।', price: 1500, comparePrice: 2000, images: ['/uploads/aqua_glide_lubricant.png'], categoryId: categories[2].id, tags: ['warming', 'tingling'], stock: 80, featured: false, theme: 'gold', specifications: { materials: 'Water-based, warming agents', finish: 'Smooth gel', frequency: 'N/A', battery: 'N/A', charging: 'N/A', userTime: 'Long-lasting', noiseLevel: 'Silent', size: '75ml', weight: '85g' }, colors: [{ name: 'Clear', hex: '#FFFFFF' }] },
      { nameEn: 'Silky Premium Lubricant', nameNe: 'सिल्की प्रीमियम लुब्रिकेन्ट', slug: 'silky-premium-lubricant', descriptionEn: 'Ultra-silky premium lube with longer lasting glide. Glycerin-free, hypoallergenic. 150ml luxury bottle with pump dispenser.', descriptionNe: 'अल्ट्रा-सिल्की प्रीमियम लुब्रिकेन्ट जो लंबे समय तक स्लाइड प्रदान करता है।', price: 2800, comparePrice: 3500, images: ['/uploads/aqua_glide_lubricant.png'], categoryId: categories[2].id, tags: ['premium', 'long-lasting'], stock: 60, featured: true, theme: 'gold', specifications: { materials: 'Silicone-based formula', finish: 'Premium smooth', frequency: 'N/A', battery: 'N/A', charging: 'N/A', userTime: 'Extra long-lasting', noiseLevel: 'Silent', size: '150ml', weight: '180g' }, colors: [{ name: 'Clear', hex: '#FFFFFF' }] },
      { nameEn: 'Bullet Vibrator Mini', nameNe: 'बुलेट भाइब्रेटर मिनी', slug: 'bullet-vibrator-mini', descriptionEn: 'Compact and powerful bullet vibrator. 5 vibration patterns, easy to use, perfect for travel. Discreet design.', descriptionNe: 'कॉम्पैक्ट और शक्तिशाली बुलेट भाइब्रेटर। 5 कंपन पैटर्न, यात्रा के लिए परफेक्ट।', price: 2200, comparePrice: 3000, images: ['/uploads/silk_touch_vibrator.png'], categoryId: categories[0].id, tags: ['travel', 'discreet'], stock: 45, featured: false, theme: 'champagne', specifications: { materials: 'ABS plastic, silicone tip', finish: 'Glossy compact', frequency: '85 Hz', battery: 'AAA x 2', charging: 'Battery powered', userTime: 'Up to 3 hours', noiseLevel: 'Less than 60 dB', size: '65 x 18 x 18 mm', weight: '28g' }, colors: [{ name: 'Champagne', hex: '#E6D3C1' }, { name: 'Silver', hex: '#C0C0C0' }] },
      { nameEn: 'Sensual Silk Bondage Set', nameNe: 'संवेदनशील सिल्क बांड सेट', slug: 'sensual-silk-bondage-set', descriptionEn: 'Premium silk restraints and blindfold set. Luxurious feel with comfortable padding. Perfect for couples exploring together.', descriptionNe: 'प्रीमियम सिल्क रिस्ट्रेंट और ब्लाइंडफोल्ड सेट।', price: 4200, comparePrice: 5500, images: ['/uploads/rose_petal_massager.png'], categoryId: categories[3].id, tags: ['bondage', 'couples'], stock: 22, featured: false, theme: 'rose-gold', specifications: { materials: '100% pure silk, padded cotton', finish: 'Luxury soft', frequency: 'N/A', battery: 'N/A', charging: 'N/A', userTime: 'Reusable', noiseLevel: 'Silent', size: 'One size fits all', weight: '120g' }, colors: [{ name: 'Midnight Black', hex: '#1A1A1A' }, { name: 'Burgundy', hex: '#800020' }, { name: 'Champagne', hex: '#E6D3C1' }] },
      { nameEn: 'Couples Vibration Ring', nameNe: 'कपल्स कंपन रिंग', slug: 'couples-vibration-ring', descriptionEn: 'Wearable vibrating ring with remote control. Perfect for public play and couples intimacy. Waterproof and rechargeable.', descriptionNe: 'दूरस्थ नियंत्रण के साथ पहनने योग्य कंपन रिंग।', price: 3800, comparePrice: 5000, images: ['/uploads/velvet_dreams_vibrator.png'], categoryId: categories[3].id, tags: ['wearable', 'remote-control'], stock: 28, featured: true, theme: 'midnight', specifications: { materials: 'Medical-grade silicone', finish: 'Sleek matte', frequency: '100 Hz', battery: 'Li-Ion 50mAh', charging: '45 minutes', userTime: 'Up to 1 hour', noiseLevel: 'Less than 50 dB', size: 'Adjustable fits all', weight: '12g' }, colors: [{ name: 'Black', hex: '#000000' }, { name: 'Gold', hex: '#FFD700' }, { name: 'Rose Gold', hex: '#B76E79' }] },
      { nameEn: 'Luxury G-Spot Vibrator', nameNe: 'लक्जरी जी-स्पॉट भाइब्रेटर', slug: 'luxury-g-spot-vibrator', descriptionEn: 'Curved design specifically for G-spot stimulation. Multiple vibration modes with memory function. Premium gift box included.', descriptionNe: 'जी-स्पॉट उत्तेजना के लिए विशेष रूप से डिज़ाइन किया गया।', price: 6200, comparePrice: 8000, images: ['/uploads/rose_petal_massager.png'], categoryId: categories[0].id, tags: ['luxury', 'g-spot'], stock: 14, featured: true, theme: 'rose-gold', specifications: { materials: 'Body-safe silicone', finish: 'Smooth glossy', frequency: '105 Hz', battery: 'Li-Ion 650mAh', charging: '2 hours', userTime: 'Up to 3 hours', noiseLevel: 'Less than 50 dB', size: '150 x 38 x 38 mm', weight: '120g' }, colors: [{ name: 'Pearl Pink', hex: '#FDEEF4' }, { name: 'Rose Gold', hex: '#B76E79' }] },
      { nameEn: 'Couples Double Vibrator', nameNe: 'कपल्स डबल भाइब्रेटर', slug: 'couples-double-vibrator', descriptionEn: 'Designed for penetrative and external stimulation simultaneously. Dual motors, 15 patterns. Control both independently with app.', descriptionNe: 'एक साथ प्रवेशकारी और बाहरी उत्तेजना के लिए डिजाइन किया गया।', price: 8500, comparePrice: 10500, images: ['/uploads/velvet_dreams_vibrator.png'], categoryId: categories[3].id, tags: ['couples', 'app-controlled', 'premium'], stock: 8, featured: true, theme: 'midnight', specifications: { materials: 'Medical-grade silicone', finish: 'Luxury matte', frequency: '115 Hz', battery: 'Li-Ion 900mAh', charging: '2.5 hours', userTime: 'Up to 4 hours', noiseLevel: 'Less than 50 dB', size: '200 x 50 x 50 mm', weight: '250g' }, colors: [{ name: 'Midnight Purple', hex: '#583D72' }, { name: 'Ocean Blue', hex: '#003366' }] },
      { nameEn: 'Seductive Red Teddy', nameNe: 'प्रलोभक लाल टेडी', slug: 'seductive-red-teddy', descriptionEn: 'Bold red teddy lingerie with straps and cutout details. Comfortable fit, easy to put on and off. Multiple sizes available.', descriptionNe: 'पट्टा और कटआउट विवरण के साथ बोल्ड लाल टेडी लिंजरी।', price: 3900, comparePrice: 5000, images: ['/uploads/rose_petal_massager.png'], categoryId: categories[5].id, tags: ['lingerie', 'sexy'], stock: 25, featured: false, theme: 'rose-gold', specifications: { materials: '85% Nylon, 15% Spandex', finish: 'Smooth satin', frequency: 'N/A', battery: 'N/A', charging: 'N/A', userTime: 'All-night wear', noiseLevel: 'Silent', size: 'S, M, L, XL, XXL', weight: '80g' }, colors: [{ name: 'Classic Red', hex: '#FF0000' }] },
      { nameEn: 'Elegant Body Stocking', nameNe: 'सुरुचिपूर्ण बॉडी स्टॉकिंग', slug: 'elegant-body-stocking', descriptionEn: 'Sheer full-body stocking with open crotch. One-size-fits-most design. Perfect for intimate evenings with your partner.', descriptionNe: 'खुली क्रॉच के साथ पारदर्शी पूर्ण शरीर मोज़ा।', price: 2800, comparePrice: 3800, images: ['/uploads/rose_petal_massager.png'], categoryId: categories[5].id, tags: ['lingerie', 'sheer'], stock: 32, featured: false, theme: 'dark', specifications: { materials: '90% Nylon, 10% Spandex', finish: 'Sheer net', frequency: 'N/A', battery: 'N/A', charging: 'N/A', userTime: 'All-night wear', noiseLevel: 'Silent', size: 'One size (fits most)', weight: '40g' }, colors: [{ name: 'Black', hex: '#000000' }, { name: 'Flesh Tone', hex: '#D4A574' }] },
      { nameEn: 'Intimate Health Supplement', nameNe: 'आंतरिक स्वास्थ्य पूरक', slug: 'intimate-health-supplement', descriptionEn: 'Natural supplement designed to enhance sexual wellness. Improves circulation and sensitivity. 30 capsules per bottle.', descriptionNe: 'यौन कल्याण बढ़ाने के लिए डिजाइन किया गया प्राकृतिक पूरक।', price: 2500, comparePrice: 3500, images: ['/uploads/aqua_glide_lubricant.png'], categoryId: categories[4].id, tags: ['wellness', 'natural'], stock: 50, featured: false, theme: 'default', specifications: { materials: 'Natural herbal ingredients', finish: 'Capsule form', frequency: 'N/A', battery: 'N/A', charging: 'N/A', userTime: 'Daily use', noiseLevel: 'N/A', size: '30 capsules', weight: '45g' }, colors: [{ name: 'White', hex: '#FFFFFF' }] },
      { nameEn: 'Advanced Kegel Balls', nameNe: 'उन्नत केगल बॉल्स', slug: 'advanced-kegel-balls', descriptionEn: 'Weighted kegel balls for pelvic floor training. Improves muscle tone and sensation. Medical-grade silicone construction.', descriptionNe: 'पैल्विक फ्लोर प्रशिक्षण के लिए भारित केगल बॉल्स।', price: 2900, comparePrice: 4000, images: ['/uploads/silk_touch_vibrator.png'], categoryId: categories[4].id, tags: ['wellness', 'kegel'], stock: 35, featured: false, theme: 'champagne', specifications: { materials: 'Medical-grade silicone', finish: 'Smooth weighted', frequency: 'N/A', battery: 'N/A', charging: 'N/A', userTime: 'Regular training', noiseLevel: 'Silent', size: '32mm diameter', weight: '120g' }, colors: [{ name: 'Rose Pink', hex: '#FF69B4' }, { name: 'Pearl White', hex: '#F5F5F5' }] },
      { nameEn: 'Premium Couples Strap-On', nameNe: 'प्रीमियम कपल्स स्ट्रैप-ऑन', slug: 'premium-couples-strap-on', descriptionEn: 'Comfortable harness with compatible attachments. Adjustable fit for all body types. Perfect for couples exploration.', descriptionNe: 'संगत अटैचमेंट के साथ आरामदायक हार्नेस।', price: 7800, comparePrice: 9500, images: ['/uploads/velvet_dreams_vibrator.png'], categoryId: categories[3].id, tags: ['couples', 'strap-on', 'premium'], stock: 10, featured: true, theme: 'midnight', specifications: { materials: 'Neoprene, medical-grade silicone', finish: 'Adjustable padded', frequency: 'N/A', battery: 'N/A', charging: 'N/A', userTime: 'Reusable', noiseLevel: 'Silent', size: 'Adjustable S-XL', weight: '380g' }, colors: [{ name: 'Black', hex: '#000000' }, { name: 'Purple', hex: '#800080' }] },
      { nameEn: 'Luxury Prostate Massager', nameNe: 'लक्जरी प्रोस्टेट मसाजर', slug: 'luxury-prostate-massager', descriptionEn: 'Curved design for targeted prostate stimulation. 7 vibration patterns, waterproof, rechargeable. Medical-grade materials.', descriptionNe: 'लक्षित प्रोस्टेट उत्तेजना के लिए घुमावदार डिजाइन।', price: 6800, comparePrice: 8500, images: ['/uploads/rose_petal_massager.png'], categoryId: categories[0].id, tags: ['prostate', 'luxury'], stock: 16, featured: true, theme: 'midnight', specifications: { materials: 'Medical-grade silicone', finish: 'Smooth matte', frequency: '100 Hz', battery: 'Li-Ion 700mAh', charging: '2 hours', userTime: 'Up to 3.5 hours', noiseLevel: 'Less than 50 dB', size: '130 x 40 x 35 mm', weight: '135g' }, colors: [{ name: 'Midnight Black', hex: '#0A0A0A' }, { name: 'Deep Purple', hex: '#583D72' }] },
      { nameEn: "Interactive Couple's App Vibrator", nameNe: 'इंटरैक्टिव कपल्स ऐप्प भाइब्रेटर', slug: 'interactive-couples-app-vibrator', descriptionEn: 'Connect with your partner remotely via app. Control vibrations from anywhere. Long-distance couples feature included.', descriptionNe: 'ऐप के माध्यम से अपने पार्टनर के साथ दूरस्थ रूप से कनेक्ट करें।', price: 8900, comparePrice: 11000, images: ['/uploads/velvet_dreams_vibrator.png'], categoryId: categories[3].id, tags: ['couples', 'app-controlled', 'long-distance'], stock: 6, featured: true, theme: 'midnight', specifications: { materials: 'Medical-grade silicone', finish: 'Premium glossy', frequency: '110 Hz', battery: 'Li-Ion 950mAh', charging: '2.5 hours', userTime: 'Up to 4 hours', noiseLevel: 'Less than 48 dB', size: '175 x 42 x 38 mm', weight: '160g' }, colors: [{ name: 'Midnight Purple', hex: '#583D72' }, { name: 'Rose Gold', hex: '#B76E79' }] },
    ];

    for (const p of products) {
      await prisma.product.create({ data: p });
    }
    console.log(`${products.length} products created`);

    console.log('\n--- Seed Complete ---');
    console.log('Admin login: admin@blissnepal.com / admin123');
    console.log('Customer login: customer@demo.com / customer123');
    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
};

seedData();
